dockerfile rework

diff --git a/PrimeC/solution_5/sieve b/PrimeC/solution_5/sieve
--- a/PrimeC/solution_5/sieve
+++ b/PrimeC/solution_5/sieve
@@ -1,8 +1,4 @@
 #!/bin/bash
-# rm -f *.s
-# rm -f *.o
-
-
 
 # Detect OS
 OS="$(uname -s)"
@@ -64,13 +60,13 @@ if [ $USE_CLANG -eq 1 ]; then
             fi
         else
             # Fallback to standard OpenMP paths when installed with libomp-dev
-            PAR="-fopenmp -lomp -I/usr/lib/gcc/x86_64-linux-gnu/14/include/ -mavx2"
+            PAR="-fopenmp -lomp -I/usr/lib/gcc/x86_64-linux-gnu/14/include/ "
         fi
     fi
 else
     COMPILER="gcc"
-    CCASM="gcc-14 $CC -S -g -Wno-psabi -masm=intel -fverbose-asm -mavx -fopt-info-vec-all=vec_report.txt"
-    CC="gcc-14 $CC -Ofast -Wno-psabi -fwhole-program -flto -s -Wl,--gc-sections -s -I/usr/lib/gcc/x86_64-linux-gnu/14/include/" # -static -Wvector-operation-performance " # for windows add this: -s -masm=intel -fverbose-asm -mavx -fopt-info-vec-all=vec_report.txt
+    CCASM="gcc $CC -S -g -Wno-psabi -masm=intel -fverbose-asm -fopt-info-vec-all=vec_report.txt" # -mavx
+    CC="gcc $CC -Ofast -Wno-psabi -fwhole-program -flto -s -Wl,--gc-sections -s -I/usr/lib/gcc/x86_64-linux-gnu/14/include/" # -static -Wvector-operation-performance " # for windows add this: -s -masm=intel -fverbose-asm -mavx -fopt-info-vec-all=vec_report.txt
     PAR="-fopenmp"
 fi
 STRIP="strip"
@@ -171,43 +167,56 @@ if [ $# -gt 0 ] && [ "$1" = "docker" ]; then
     if [ $# -gt 1 ]; then
         DOCKER_TYPE="$2"
         if [ "$DOCKER_TYPE" = "all" ]; then
-            # Loop through all Dockerfiles in ./dev/docker
             for DOCKERFILE in ./dev/docker/Dockerfile_*; do
+                if [[ "$DOCKERFILE" == *"Dockerfile_common"* ]]; then
+                    continue
+                fi
                 EXTENSION="${DOCKERFILE#*Dockerfile_}" # Extract the extension
-                if [ $verbose_level -gt 1 ]; then
-                    echo "Building and running Docker container for type: $EXTENSION"
-                    echo "Running command: docker build --pull --rm -f $DOCKERFILE -t sieve-$EXTENSION ." 
-                fi
-                
-                # Build the Docker image
-                docker build --pull --rm -f "$DOCKERFILE" -t "sieve-$EXTENSION" . 2> ./dev/build.log
-                if [ $? -ne 0 ]; then
-                    echo "Error: Docker build failed for $EXTENSION."
-                    exit 1
-                fi
-                
-                # Run the Docker container with any remaining arguments
-                if [ $verbose_level -gt 1 ]; then
-                    echo "Running Docker container with arguments: $@"
-                fi
-                docker run --rm -e DOCKERFILE_TYPE="$EXTENSION" "sieve-$EXTENSION" "${@:3}"
-                if [ $? -ne 0 ]; then
-                    echo "Error: Docker run failed for $EXTENSION."
-                    exit 1
-                fi
+                # RUN the same command line again, but "all" is replaced with the actual extension
+                $0 docker "$EXTENSION" "${@:3}"
+
             done
-            exit 0
+
+            # # Loop through all Dockerfiles in ./dev/docker
+            # for DOCKERFILE in ./dev/docker/Dockerfile_*; do
+            #     EXTENSION="${DOCKERFILE#*Dockerfile_}" # Extract the extension
+            #     if [ $verbose_level -gt 1 ]; then
+            #         echo "Building and running Docker container for type: $EXTENSION"
+            #         echo "Running command: docker build --pull --rm -f $DOCKERFILE -t sieve-$EXTENSION ." 
+            #     fi
+                
+            #     # Build the Docker image
+            #     docker build --pull --rm -f "$DOCKERFILE" -t "sieve-$EXTENSION" . 2> ./dev/build/docker.log
+            #     if [ $? -ne 0 ]; then
+            #         echo "Error: Docker build failed for $EXTENSION."
+            #         exit 1
+            #     fi
+                
+            #     # Run the Docker container with any remaining arguments
+            #     if [ $verbose_level -gt 1 ]; then
+            #         echo "Running Docker container with arguments: $@"
+            #     fi
+            #     docker run --rm -e DOCKERFILE_TYPE="$EXTENSION" "sieve-$EXTENSION" "${@:3}"
+            #     if [ $? -ne 0 ]; then
+            #         echo "Error: Docker run failed for $EXTENSION."
+            #         exit 1
+            #     fi
+            # done
+            # exit 0
         fi
 
         DOCKERFILE="dev/docker/Dockerfile_$DOCKER_TYPE"
         if [ $verbose_level -gt 1 ]; then
             echo "Building and running Docker container for type: $DOCKER_TYPE"
-            echo "Running command: docker build --pull --rm -f $DOCKERFILE -t sieve-$DOCKER_TYPE ." 
+            echo "Running command: docker build --pull --rm -t sieve-$DOCKER_TYPE ." 
         fi
         
         if [ -f "$DOCKERFILE" ]; then
             # Build the Docker image
-            docker build --pull --rm -f "$DOCKERFILE" -t "sieve-$DOCKER_TYPE" . 2> ./dev/build.log
+            cat "$DOCKERFILE" > Dockerfile
+            echo "" >> Dockerfile
+            cat "./dev/docker/Dockerfile_common" >> Dockerfile
+            docker build --pull --rm -t "sieve_$DOCKER_TYPE" . 2> ./dev/build.log
             if [ $? -ne 0 ]; then
                 echo "Error: Docker build failed."
                 exit 1
@@ -219,10 +228,10 @@ if [ $# -gt 0 ] && [ "$1" = "docker" ]; then
             # Run the Docker container with any remaining arguments
             if [ $verbose_level -gt 1 ]; then
                 echo "Running Docker container with arguments: $@"
-                echo "Run with: docker run --rm -e DOCKERFILE_TYPE=\"$DOCKER_TYPE\" \"sieve-$DOCKER_TYPE\" \"$@\""
-                echo "Go in with: docker run --rm -e DOCKERFILE_TYPE=$DOCKER_TYPE -it --entrypoint /bin/bash sieve-$DOCKER_TYPE"  
+                echo "Run with: docker run --rm -e DOCKERFILE_TYPE=\"$DOCKER_TYPE\" \"sieve_$DOCKER_TYPE\" \"$@\""
+                echo "Go in with: docker run --rm --name "sieve_$DOCKER_TYPE" -e DOCKERFILE_TYPE=$DOCKER_TYPE -it --entrypoint /bin/bash sieve_$DOCKER_TYPE"  
             fi
-            docker run --rm -e DOCKERFILE_TYPE="$DOCKER_TYPE" "sieve-$DOCKER_TYPE" "$@"
+            docker run --rm --name "sieve_$DOCKER_TYPE" -e DOCKERFILE_TYPE="$DOCKER_TYPE" "sieve_$DOCKER_TYPE" "$@"
             exit $?
         else
             echo "Error: Dockerfile '$DOCKERFILE' not found."
@@ -256,7 +265,7 @@ PROGTOTAL="${base}-${set_x}-${set_y}-${set_z}"
 # fi
 $CC -o ./bin/$PROGTOTAL ./src/${base}.c $DEFINE_FLAGS
 if [ "$COMPILTER" = "gcc" ]; then
-    $CCASM -o ./build/$PROGTOTAL.s ./src/${base}.c $DEFINE_FLAGS
+    $CCASM -o ./dev/build/$PROGTOTAL.s ./src/${base}.c $DEFINE_FLAGS
 fi
 if [ $? -ne 0 ]; then
     echo "Error: Compilation failed for sequential version."
